### ISSUE TITLE
gsync

### ISSUE THREAD

**Issue by capriciousduck** [labbots/google-drive-upload#73] opened 2020-06-24 09:31 UTC
How do I install gsync for background sync?

**Comment by Akianonymus** [comment] 2020-06-24 09:36
@capriciousduck It is installed automatically when gupload is installed.

try `gsync --help`

**Comment by capriciousduck** [comment] 2020-06-24 10:40
I want to upload to the root folder. Should I use "root" as the folder name?

**Comment by Akianonymus** [comment] 2020-06-24 11:40
@capriciousduck Currently not possible, i have added a fix in my pull request.

**Comment by capriciousduck** [comment] 2020-06-24 11:55
Can I use any name as the folder name or should I use a name which is in my google drive?

**Comment by Akianonymus** [comment] 2020-06-24 12:04
> Can I use any name as the folder name or should I use a name which is in my google drive?

Both are good, whatever you want.

**Comment by capriciousduck** [comment] 2020-06-24 15:12
How do I run the sync on startup? Using rc.local?

**Comment by capriciousduck** [comment] 2020-06-24 15:55
Will the files be deleted after syncing the file?

**Comment by Akianonymus** [comment] 2020-06-25 03:27
@capriciousduck No, script just uploads it, nothing else.

**Comment by Akianonymus** [comment] 2020-06-25 03:27
@capriciousduck Will try to add soon

**Comment by Akianonymus** [comment] 2020-06-25 04:29
@capriciousduck Can you try this and report ??

Guide: https://github.com/Akianonymus/google-drive-upload/tree/fix#background-sync-jobs

systemd file: https://github.com/Akianonymus/google-drive-upload/raw/fix/gsync.service

**Comment by Akianonymus** [comment] 2020-06-25 13:56
@capriciousduck did you test ? 🤔

**Comment by capriciousduck** [comment] 2020-06-25 14:19
Actually, I forgot. Sorry. I'll try right now and report you.

**Comment by capriciousduck** [comment] 2020-06-25 14:53
Unable to boot up. It's failing.

`gsync.service - google-drive-upload synchronisation service
   Loaded: loaded (/etc/systemd/system/gsync.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-06-25 14:40:57 UTC; 1min 0s ago
  Process: 5573 ExecStart=/root/.google-drive-upload/bin/gsync /mnt/systemdisk/sync (code=exited, status=1/FAILURE)
 Main PID: 5573 (code=exited, status=1/FAILURE)

Jun 25 14:40:57 zeus systemd[1]: gsync.service: Service hold-off time over, scheduling restart.
Jun 25 14:40:57 zeus systemd[1]: gsync.service: Scheduled restart job, restart counter is at 5.
Jun 25 14:40:57 zeus systemd[1]: Stopped google-drive-upload synchronisation service.
Jun 25 14:40:57 zeus systemd[1]: gsync.service: Start request repeated too quickly.
Jun 25 14:40:57 zeus systemd[1]: gsync.service: Failed with result 'exit-code'.
Jun 25 14:40:57 zeus systemd[1]: Failed to start google-drive-upload synchronisation service.`


Here's how my systemd file looks like:

`[Unit]
Description=google-drive-upload synchronisation service
After=network.target

[Service]
Type=simple
User=root
Restart=always
RestartSec=1
ExecStart=/root/.google-drive-upload/bin/gsync /mnt/systemdisk/sync
ExecStop=/root/.google-drive-upload/bin/gsync /mnt/systemdisk/sync --kill

[Install]
WantedBy=multi-user.target`

**Comment by capriciousduck** [comment] 2020-06-25 14:54
You're doing a great job, Aki. And I'm from India too O:)

**Comment by Akianonymus** [comment] 2020-06-25 17:31
@capriciousduck try below in systemd file

```
[Unit]
Description=google-drive-upload synchronisation service
After=network.target

[Service]
Type=simple
User=root
Restart=always
RestartSec=1
ExecStart=/usr/bin/bash '/root/.google-drive-upload/bin/gsync' '/mnt/systemdisk/sync'
ExecStop=/usr/bin/bash '/root/.google-drive-upload/bin/gsync' '/mnt/systemdisk/sync' --kill

[Install]
WantedBy=multi-user.target
```

**Comment by capriciousduck** [comment] 2020-06-26 08:53
Nope. Still not working.

> gsync.service - google-drive-upload synchronisation service
   Loaded: loaded (/etc/systemd/system/gsync.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-06-26 08:52:19 UTC; 16s ago
  Process: 7318 ExecStart=/usr/bin/env bash /root/.google-drive-upload/bin/gsync /mnt/systemdisk/sync (code=exited, status=1/FAILURE)
 Main PID: 7318 (code=exited, status=1/FAILURE)

Jun 26 08:52:19 zeus systemd[1]: gsync.service: Service hold-off time over, scheduling restart.
Jun 26 08:52:19 zeus systemd[1]: gsync.service: Scheduled restart job, restart counter is at 5.
Jun 26 08:52:19 zeus systemd[1]: Stopped google-drive-upload synchronisation service.
Jun 26 08:52:19 zeus systemd[1]: gsync.service: Start request repeated too quickly.
Jun 26 08:52:19 zeus systemd[1]: gsync.service: Failed with result 'exit-code'.
Jun 26 08:52:19 zeus systemd[1]: Failed to start google-drive-upload synchronisation service.

**Comment by Akianonymus** [comment] 2020-06-26 10:31
@capriciousduck 

add this in systemd file


```
[Unit]
Description=google-drive-upload synchronisation service
After=network.target

[Service]
Type=simple
User=root
Restart=on-abort
RestartSec=3
ExecStart=/root/startgsync.sh

[Install]
WantedBy=multi-user.target

```

then run the below commands


```
SCRIPT='#!/usr/bin/env bash

GSYNC_SCRIPT="/root/.google-drive-upload/bin/gsync"
LOCAL_FOLDER="/mnt/systemdisk/sync"
DRIVE_FOLDER=""
REST_ARGUMENTS=""

"${GSYNC_SCRIPT}" ${LOCAL_FOLDER} ${DRIVE_FOLDER:+-d ${DRIVE_FOLDER}} ${REST_ARGUMENTS} --logs'

printf "%s\n" "${SCRIPT}" >| "/root/startgsync.sh"

```

try to start the systemd service, send logs

**Comment by capriciousduck** [comment] 2020-06-26 11:59
`● gsync.service - google-drive-upload synchronisation service
   Loaded: loaded (/etc/systemd/system/gsync.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-06-26 11:56:12 UTC; 6s ago
  Process: 9371 ExecStart=/mnt/systemdisk/sync/startgsync.sh (code=exited, status=203/EXEC)
 Main PID: 9371 (code=exited, status=203/EXEC)

Jun 26 11:56:12 zeus systemd[1]: Started google-drive-upload synchronisation service.
Jun 26 11:56:12 zeus systemd[9371]: gsync.service: Failed to execute command: Permission denied
Jun 26 11:56:12 zeus systemd[9371]: gsync.service: Failed at step EXEC spawning /mnt/systemdisk/sync/startgsync.sh: Permission denied
Jun 26 11:56:12 zeus systemd[1]: gsync.service: Main process exited, code=exited, status=203/EXEC
Jun 26 11:56:12 zeus systemd[1]: gsync.service: Failed with result 'exit-code'.`

**Comment by capriciousduck** [comment] 2020-06-26 12:00
Given executable permissions and tried to run, then I got this.

`root@zeus:~# systemctl status gsync
● gsync.service - google-drive-upload synchronisation service
   Loaded: error (Reason: Exec format error)
   Active: failed (Result: exit-code) since Fri 2020-06-26 11:57:30 UTC; 17s ago
 Main PID: 9573 (code=exited, status=1/FAILURE)

Jun 26 11:57:30 zeus systemd[1]: Started google-drive-upload synchronisation service.
Jun 26 11:57:30 zeus startgsync.sh[9573]: Error: gupload is not installed, use -c/--command to specify.
Jun 26 11:57:30 zeus systemd[1]: gsync.service: Main process exited, code=exited, status=1/FAILURE
Jun 26 11:57:30 zeus systemd[1]: gsync.service: Failed with result 'exit-code'.
Jun 26 11:57:37 zeus systemd[1]: /etc/systemd/system/gsync.service:10: Executable path is not absolute: ./mnt/systemdisk/sync/startgsync.sh`

**Comment by capriciousduck** [comment] 2020-06-26 12:01
Fixed some things and again tried to run. Then I got this.

`gsync.service - google-drive-upload synchronisation service
   Loaded: error (Reason: Exec format error)
   Active: failed (Result: exit-code) since Fri 2020-06-26 11:57:30 UTC; 50s ago
 Main PID: 9573 (code=exited, status=1/FAILURE)

Jun 26 11:57:30 zeus systemd[1]: Started google-drive-upload synchronisation service.
Jun 26 11:57:30 zeus startgsync.sh[9573]: Error: gupload is not installed, use -c/--command to specify.
Jun 26 11:57:30 zeus systemd[1]: gsync.service: Main process exited, code=exited, status=1/FAILURE
Jun 26 11:57:30 zeus systemd[1]: gsync.service: Failed with result 'exit-code'.
Jun 26 11:57:37 zeus systemd[1]: /etc/systemd/system/gsync.service:10: Executable path is not absolute: ./mnt/systemdisk/sync/startgsync.sh
Jun 26 11:58:11 zeus systemd[1]: /etc/systemd/system/gsync.service:10: Executable path is not absolute: sh /mnt/systemdisk/sync/startgsync.sh`

**Comment by capriciousduck** [comment] 2020-06-26 12:02
It appears to me that startsync.sh is not able to detect the installed upload. In the first line of the above log says "gupload is not installed." when I do have gupload installed.

**Comment by Akianonymus** [comment] 2020-06-26 15:03
@capriciousduck try adding `source /root/.bashrc` at the second line of startgsync.sh script

**Comment by capriciousduck** [comment] 2020-06-26 15:42
Still not able to start.

`gsync.service - google-drive-upload synchronisation service
   Loaded: loaded (/etc/systemd/system/gsync.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-06-26 15:41:31 UTC; 4s ago
  Process: 43304 ExecStart=/mnt/systemdisk/sync/startgsync.sh (code=exited, status=1/FAILURE)
 Main PID: 43304 (code=exited, status=1/FAILURE)

Jun 26 15:41:31 zeus systemd[1]: Started google-drive-upload synchronisation service.
Jun 26 15:41:31 zeus startgsync.sh[43304]: Error: gupload is not installed, use -c/--command to specify.
Jun 26 15:41:31 zeus systemd[1]: gsync.service: Main process exited, code=exited, status=1/FAILURE
Jun 26 15:41:31 zeus systemd[1]: gsync.service: Failed with result 'exit-code'.`

**Comment by Akianonymus** [comment] 2020-06-26 16:48
@capriciousduck do this command and try running the service again

do this command in normal terminal

```
sed "s|\${COMMAND_NAME}|$(command -v gupload)|g" -i "$(command -v gsync)"

```

I currently don't have access to a proper linux environment, so can't test myself.

**Comment by capriciousduck** [comment] 2020-06-26 17:17
I've just switched my laptop off. I'll try in the morning. If you don't mind I can provide you a linux server. Either on digitalocean or webdock. Let me know what you think.

**Comment by capriciousduck** [comment] 2020-06-27 14:23
It is working now!!!

`root@zeus:~# systemctl status gsync
● gsync.service - google-drive-upload synchronisation service
   Loaded: loaded (/etc/systemd/system/gsync.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2020-06-27 14:23:00 UTC; 13s ago
 Main PID: 132255 (bash)
    Tasks: 4 (limit: 464185)
   CGroup: /system.slice/gsync.service
           ├─132255 bash /mnt/systemdisk/sync/startgsync.sh
           ├─132256 bash /root/.google-drive-upload/bin/gsync /mnt/systemdisk/sync --logs
           ├─132263 bash /root/.google-drive-upload/bin/gsync /mnt/systemdisk/sync --logs
           └─132267 tail -f /root/.google-drive-upload/sync/sync/mnt/systemdisk/sync/logs

Jun 27 14:23:00 zeus systemd[1]: Started google-drive-upload synchronisation service.
Jun 27 14:23:00 zeus startgsync.sh[132255]: Job started.
Jun 27 14:23:00 zeus startgsync.sh[132255]: Local Folder: /mnt/systemdisk/sync
Jun 27 14:23:00 zeus startgsync.sh[132255]: Drive Folder: sync
Jun 27 14:23:00 zeus startgsync.sh[132255]: PID: 132263
Jun 27 14:23:04 zeus startgsync.sh[132255]: startgsync.sh | 279 Bytes | Uploaded
Jun 27 14:23:04 zeus startgsync.sh[132255]:  Time Elapsed: 0 minute(s) and 4 seconds.`

**Comment by Akianonymus** [comment] 2020-06-27 15:17
@capriciousduck Aah, thx for consideration, although i got my server back.

Will ping you in future if i need :)

**Comment by Akianonymus** [comment] 2020-06-27 15:18
@capriciousduck I have made a new pr, including the fixes and automated script generation for systemd services.

Read https://github.com/Akianonymus/google-drive-upload/tree/fix#background-sync-jobs

**Comment by capriciousduck** [comment] 2020-06-27 15:56
> @capriciousduck Aah, thx for consideration, although i got my server back.
> 
> Will ping you in future if i need :)

Alright!

**Comment by capriciousduck** [comment] 2020-06-27 15:57
> @capriciousduck I have made a new pr, including the fixes and automated script generation for systemd services.
> 
> Read https://github.com/Akianonymus/google-drive-upload/tree/fix#background-sync-jobs
> 
> To test out
> 
> ```
> bash <(curl --compressed -s https://raw.githubusercontent.com/labbots/google-drive-upload/master/install.sh) -r Akianonymus/google-drive-upload -B fix
> ```

Ok. I'll test. I guess I'll re-install the script freshly :)

**Comment by capriciousduck** [comment] 2020-06-28 10:26
I've just tested the fix now. And it is working.

**Comment by labbots** [comment] 2020-06-30 10:01
@capriciousduck @Akianonymus I am closing this ticket as the issue is resolved now.

**Closed by labbots** 2020-06-30 10:01 UTC
