### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by capriciousduck** [labbots/google-drive-upload#64] opened 2020-06-08 15:23 UTC
I get the following error while trying to update the script.

`gupload -u
63: --: Unknown option
Try 63 -h/--help for more information.`

**Comment by Akianonymus** [comment] 2020-06-09 01:53
> I get the following error while trying to update the script.
> 
> `gupload -u 63: --: Unknown option Try 63 -h/--help for more information.`
```
bash <(curl --compressed -s https://raw.githubusercontent.com/labbots/google-drive-upload/master/install.sh)
```
Try this, afterwards, -u flag should as it is meant to be.

**Comment by Akianonymus** [comment] 2020-06-09 02:33
Will be fixed in after next release

**Comment by capriciousduck** [comment] 2020-06-09 16:21
I installed the updated script on another server. Still, I get the same error when I execute the update command.

**Comment by Akianonymus** [comment] 2020-06-10 02:29
@labbots you need to make a new release, then only the fix will work

**Comment by capriciousduck** [comment] 2020-06-10 06:47
Sorry, what do you mean by a new release? You mean I need to freshly install on a machine?

**Comment by labbots** [comment] 2020-06-10 08:45
@Akianonymus @capriciousduck I have created a new release v2.6.1.

**Comment by capriciousduck** [comment] 2020-06-10 08:55
How do I uninstall the script?. The uninstall flag("gupload -U) also doesn't work.

**Comment by labbots** [comment] 2020-06-10 09:19
@capriciousduck you could install the latest release by running the following command
`bash <(curl --compressed -s https://raw.githubusercontent.com/labbots/google-drive-upload/master/install.sh)`

**Comment by Akianonymus** [comment] 2020-06-10 11:43
@capriciousduck Works here 🤔, strange.

**Comment by Akianonymus** [comment] 2020-06-24 05:59
This should be closed as the issue is fixed.

**Closed** 2020-06-24 09:30 UTC
